services:
  - type: web
    name: ghlink-converter-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_UPLOAD_MB
        value: 100
